### ISSUE TITLE
Profitability switch not considering dual-mining

### ISSUE THREAD

**Issue by bettimms** [angelbbs/NiceHashMinerLegacy#125]
When enabling all algorithms, automatic profitability switching will not run on dual-mining despite that it may be the most profitable one at certain time. (Tested with DaggerAutolykos since other algorithms seems are missing and there's already an open issue for that)

**Comment by Evilb0rg** [comment]
For me it does work. Both DaggerKawpow and DaggerAutolykos seam to work very well with my 3060's. They mostly on the dual miner since I got them tuned in.  Well except for DaggerOctopus as the Nicehash stratum points to stratum2 which gives error.
Just make sure when you save any changes to the MLFF that you also restart it. It wont apply the saved settings till its restarted. 
I noticed that as well when enabling algos that it wouldn't use them until restart. 
 I personally changed my switching to 3min at 2.0% from obtaining all sources.. as this is the most stable. If on 1 min they miner might go into constantly switching and you will loose profit. 
Hope this helps.

**Comment by bettimms** [comment]
Strange. I tested on 3080 LHR and i get only DaggerAutolykos algo in the list. I've default switching algorithm to 5min. with threshold at 5% but not seeing that it's picking it. I'm just disabling all others when i want to run the dual mining.

**Comment by Evilb0rg** [comment]
Weird indeed..  5% and 5 min seams a bit high. Have you tried lowering it to see if that works?

**Comment by bettimms** [comment]
Changed to 3min. and threshold to 2% but same thing, not picking it up. Im just testing it manually and I'm seeing that the dual one is more profitable most of the time compared to others. But when I enable all the dual one is not picked.

**Comment by bettimms** [comment]
Apparently it's working after I changed the parameters to `--lhr-algo` and benchmarked it with precise.

**Comment by Evilb0rg** [comment]
Nice. Glad you got it fixed..:)

**Comment by bettimms** [comment]
> Nice. Glad you got it fixed..:)

Thanks. The only challenge seems to stabilize the temps. I’ve an Asus Tuf 3080 that has 54 C the GPU temp but has 104C the memory temp. Such a huge gap.
